server:
  port: 8083

spring:
  application:
    name: ms-rdv
  datasource:
    url: jdbc:mysql://localhost:3307/ms_rdv_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Africa/Casablanca
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

jwt:
  # Doit être identique au secret de ms-auth pour valider les tokens JWT émis par ms-auth
  secret: ${JWT_SECRET:medsys-hospital-jwt-secret-key-2026-very-long-and-secure-string-please-change-in-prod}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  ms-patient-url: http://localhost:8081
  ms-auth-url: http://localhost:8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
