server:
  port: 8083

spring:
  application:
    name: ms-rdv

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ms_rdv_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Africa/Casablanca}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

jwt:
  secret: ${JWT_SECRET:medsys-hospital-jwt-secret-key-2026-very-long-and-secure-production-key-minimum-256-bits}
  expiration: 900000

app:
  ms-patient-url: ${APP_MS_PATIENT_URL:http://localhost:8081}
  ms-auth-url: ${APP_MS_AUTH_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
